### ISSUE TITLE
jellyfin-mpv-desktop no start in Kde (pip)

### ISSUE THREAD

**Issue by txutxifel** [jellyfin/jellyfin-mpv-shim#154]
**Describe the bug**
jellyfin-mpv-desktop no start in Kde in Opensuse Leap 15.2, i got this error:

```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
Violación de segmento (`core' generado)
```
However Its installed correctly, It starts in icewm. 

1. Execute /usr/bin/jellfin-mvp-desktop
2. Crash
3. See error

**Expected behavior**
Program starts

**Desktop (please complete the following information):**
 - OS: Opensuse
 - Version leap 15.2

**Comment by ahmed2m** [comment]
same here with `jellyfin-mpv-shim`

```shell
[ahmed@probook ~]$ jellyfin-mpv-shim 
2021-01-26 02:13:08,494 [    INFO] conf: Loaded settings from json: /home/ahmed/.config/jellyfin-mpv-shim/conf.json
2021-01-26 02:13:08,623 [    INFO] player: Using external mpv playback backend.
2021-01-26 02:13:08,624 [   DEBUG] mpv-jsonipc: Staring MPV from mpv.
2021-01-26 02:13:08,624 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv46303912768480 for MPV.
2021-01-26 02:13:08,827 [   DEBUG] mpv-jsonipc: Found MPV socket.
2021-01-26 02:13:09,337 [    INFO] werkzeug: 127.0.0.1 - - [26/Jan/2021 02:13:09] "GET /index.html HTTP/1.1" 200 -
QSettings::value: Empty key passed
QSettings::value: Empty key passed
Segmentation fault (core dumped)

```

**Comment by iwalton3** [comment]
Did you set the config option to enable desktop in `/home/ahmed/.config/jellyfin-mpv-shim/conf.json`?

**Comment by ahmed2m** [comment]
> Did you set the config option to enable desktop in `/home/ahmed/.config/jellyfin-mpv-shim/conf.json`?

Oh! apparently I did and I forgot about it, now that it is disabled I can see the systray but It doesn't seem to connect to the server I configured early (when mpv-shim was working for me) and 'Configure Servers' from the systray doesn't open any window (I have tk installed)

```py
[ahmed@probook ~]$ jellyfin-mpv-shim 
2021-01-26 02:26:05,749 [    INFO] conf: Loaded settings from json: /home/ahmed/.config/jellyfin-mpv-shim/conf.json
2021-01-26 02:26:05,776 [    INFO] player: Using external mpv playback backend.
2021-01-26 02:26:05,777 [   DEBUG] mpv-jsonipc: Staring MPV from mpv.
2021-01-26 02:26:05,777 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv149162837818994 for MPV.
2021-01-26 02:26:05,879 [   DEBUG] mpv-jsonipc: Found MPV socket.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/site-packages/jellyfin_mpv_shim/gui_mgr.py", line 179, in run
    self.queue = Queue()
  File "/usr/lib/python3.9/multiprocessing/context.py", line 102, in Queue
    from .queues import Queue
ImportError: cannot import name 'Queue' from partially initialized module 'multiprocessing.queues' (most likely due to a circular import) (/usr/lib/python3.9/multiprocessing/queues.py)
2021-01-26 02:26:06,014 [   DEBUG] PIL.PngImagePlugin: STREAM "b'IHDR'" 16 13
2021-01-26 02:26:06,014 [   DEBUG] PIL.PngImagePlugin: STREAM "b'pHYs'" 41 9
2021-01-26 02:26:06,014 [   DEBUG] PIL.PngImagePlugin: STREAM "b'IDAT'" 62 709
```

**Comment by iwalton3** [comment]
I've never run it on python 3.9 so it could be that.

**Comment by txutxifel** [comment]
Hi,
I fix it by myself.  I delete  PyQt5 folder
in:
/usr/lib64/python3.6/site-packages/
and i reinstalled the package.
python3-qt5 (in Opensuse)

Now, it's working perfectly.

I hope this helps others.

Cheers and thanks

**Comment by baddwin** [comment]
I also encountered this issue in Fedora when I installed `python3-qt5-webkit`.
It solved after replacing it with `python3-qt5-webengine`.

**Comment by Nocifer** [comment]
I also just encountered this problem, and it only started when I switched from a Gnome to a KDE session. This is what I've found (this is in a Arch Linux/Python 3.9 environment):

1) Removing pyqt5 and pyqt5-sip results in the following error about PyQt5 missing, but jellyfin-mpv-desktop launches successfully:

> 2021-03-27 15:33:24,200 [    INFO] conf: Loaded settings from json: /home/nocifer/.config/jellyfin-mpv-shim/conf.json
2021-03-27 15:33:24,276 [    INFO] player: Using libmpv1 playback backend.
2021-03-27 15:33:24,569 [    INFO] werkzeug: 127.0.0.1 - - [27/Mar/2021 15:33:24] "GET /index.html HTTP/1.1" 200 -
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/webview/guilib.py", line 29, in import_qt
    import webview.platforms.qt as guilib
  File "/usr/lib/python3.9/site-packages/webview/platforms/qt.py", line 29, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5'
2021-03-27 15:33:24,570 [   ERROR] pywebview: QT cannot be loaded
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/webview/guilib.py", line 29, in import_qt
    import webview.platforms.qt as guilib
  File "/usr/lib/python3.9/site-packages/webview/platforms/qt.py", line 29, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5'
2021-03-27 15:33:25,077 [    INFO] werkzeug: 127.0.0.1 - - [27/Mar/2021 15:33:25] "GET /index.html HTTP/1.1" 200 -
2021-03-27 15:33:25,148 [    INFO] werkzeug: 127.0.0.1 - - [27/Mar/2021 15:33:25] "GET /config.json HTTP/1.1" 304 -
2021-03-27 15:33:25,338 [    INFO] webclient: Recieved session for server: ArchBox, user: Nocifer
...

2) Reinstalling pyqt5 without pyqt5-sip results in the following error about PyQt5-SIP missing, but jellyfin-mpv-desktop also launches successfully:

> 2021-03-27 15:34:21,022 [    INFO] conf: Loaded settings from json: /home/nocifer/.config/jellyfin-mpv-shim/conf.json
2021-03-27 15:34:21,099 [    INFO] player: Using libmpv1 playback backend.
2021-03-27 15:34:21,401 [    INFO] werkzeug: 127.0.0.1 - - [27/Mar/2021 15:34:21] "GET /index.html HTTP/1.1" 200 -
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/webview/guilib.py", line 29, in import_qt
    import webview.platforms.qt as guilib
  File "/usr/lib/python3.9/site-packages/webview/platforms/qt.py", line 29, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5.sip'
2021-03-27 15:34:21,402 [   ERROR] pywebview: QT cannot be loaded
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/webview/guilib.py", line 29, in import_qt
    import webview.platforms.qt as guilib
  File "/usr/lib/python3.9/site-packages/webview/platforms/qt.py", line 29, in <module>
    from PyQt5 import QtCore
**ModuleNotFoundError: No module named 'PyQt5.sip'**
2021-03-27 15:34:21,911 [    INFO] werkzeug: 127.0.0.1 - - [27/Mar/2021 15:34:21] "GET /index.html HTTP/1.1" 200 -
2021-03-27 15:34:21,982 [    INFO] werkzeug: 127.0.0.1 - - [27/Mar/2021 15:34:21] "GET /config.json HTTP/1.1" 304 -
2021-03-27 15:34:22,182 [    INFO] webclient: Recieved session for server: ArchBox, user: Nocifer
...

3) Reinstalling pyqt5-sip results in the error originally reported, and jellyfin-mpv-desktop stops working:

> 2021-03-27 15:34:52,165 [    INFO] conf: Loaded settings from json: /home/nocifer/.config/jellyfin-mpv-shim/conf.json
2021-03-27 15:34:52,245 [    INFO] player: Using libmpv1 playback backend.
2021-03-27 15:34:52,601 [    INFO] werkzeug: 127.0.0.1 - - [27/Mar/2021 15:34:52] "GET /index.html HTTP/1.1" 200 -
QSettings::value: Empty key passed
QSettings::value: Empty key passed
[1]    120104 segmentation fault (core dumped)  jellyfin-mpv-desktop

**Comment by iwalton3** [comment]
I would guess that only GTK Webkit works then. You could try reporting the issue to upstream pywebview but it may be easier for me to switch to QT WebEngine across the board instead,

**Comment by Nocifer** [comment]
Nah no worries, there is a solution after all: you just need to have pyqtwebengine installed, which (on Arch at least) is an optional dependency for pywebview that's needed in order for it to run in a Qt environment. Install that, problem solved :)

**Comment by iwalton3** [comment]
That's good to hear. Annoying that it doesn't tell you that.

**Comment by iwalton3** [comment]
Desktop mode is now unsupported and is removed in the latest release. Please use Shim Mode or [Jellyfin Media Player](https://github.com/jellyfin/jellyfin-media-player/releases) instead.
