### ISSUE TITLE
Unable to connect to jellyfin server / https with self signed certificates

### ISSUE THREAD

**Issue by aljazzair** [jellyfin/jellyfin-mpv-shim#236]
**Describe the bug**
Unable to connect to jellyfin server / https with self signed certificates from pfsense.

**To Reproduce**

1. pamac/yay install

2. start jellyfin-mpv-shim from cli

3. Enter server https URL and credentials: https://mediaserver.mydomain:1234/jellyfin JELLOUSER jellopassword

4. Try several combinations of the same URL with or without trailing / with or without /jellyfin with domain name or IP

4. See error **"could not add server. Please check your connection information"**

5. Try the same https server from the same client via several browsers and wget, it works.
```
wget https://mediaserver.mydomain:1234/jellyfin/web/index.html
--2021-10-05 09:20:41--  https://mediaserver.mydomain:1234/jellyfin/web/index.html
SSL_INIT
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving spree.mydomain (mediaserver.mydomain)... 192.0.0.192
Connecting to spree.mydomain (mediaserver.mydomain)|192.0.0.192|:1234... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6912 (6.8K) [text/html]
Saving to: ‘index.html’

index.html     100%[========================>]   6.75K  --.-KB/s    in 0s      


2021-10-05 09:20:41 (174 MB/s) - ‘index.html’ saved [6912/6912]
```

7. Looking at the logs, there is an SSL certificate error shown:

` Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)`

**Expected behavior**

Expect the app to connect to the https server

**Desktop (please complete the following information):**

 - OS: Linux clientcomputer 5.13.19-2-MANJARO #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64 GNU/Linux
 - Version  2.0.1-1 from Arch AUR

**Full log** (edited for privacy)

```
2021-10-05 09:02:37,597 [    INFO] conf: Loaded settings from json: /home/username/.config/jellyfin-mpv-shim/conf.json
2021-10-05 09:02:37,652 [    INFO] player: Using libmpv1 playback backend.
2021-10-05 09:02:37,671 [   ERROR] menu: Could not load profile manager.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/jellyfin_mpv_shim/menu.py", line 79, in __init__
    self.profile_manager = VideoProfileManager(self, player_manager, player)
  File "/usr/lib/python3.9/site-packages/jellyfin_mpv_shim/video_profile.py", line 61, in __init__
    raise FileNotFoundError("Could not find default shader pack.")
FileNotFoundError: Could not find default shader pack.
2021-10-05 09:02:37,767 [   DEBUG] PIL.PngImagePlugin: STREAM "b'IHDR'" 16 13
2021-10-05 09:02:37,767 [   DEBUG] PIL.PngImagePlugin: STREAM "b'pHYs'" 41 9
2021-10-05 09:02:37,767 [   DEBUG] PIL.PngImagePlugin: STREAM "b'IDAT'" 62 709

(jellyfin-mpv-shim:966217): GLib-GIO-CRITICAL **: 09:02:37.825: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
2021-10-05 09:02:59,147 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.client: JellyfinClient initializing...
2021-10-05 09:02:59,148 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Configuration initializing...
2021-10-05 09:02:59,148 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin http constructor.
2021-10-05 09:02:59,148 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: WSClient initializing...
2021-10-05 09:02:59,148 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: ConnectionManager initializing...
2021-10-05 09:02:59,148 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: Credentials initializing...
2021-10-05 09:02:59,148 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin app constructor.
2021-10-05 09:02:59,148 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2021-10-05 09:02:59,148 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2021-10-05 09:02:59,148 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 'X-Application': 'Jellyfin MPV Shim/2.0.1', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/2.0.1', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=clientcomputer, DeviceId=EEEE-AAAA-ZZZZ-XXXX-DDDD, Version=2.0.1'}
2021-10-05 09:02:59,151 [   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): mediaserver.mydomain:1234
2021-10-05 09:02:59,208 [   ERROR] JELLYFIN.jellyfin_apiclient_python.connection_manager: HTTPSConnectionPool(host='mediaserver.mydomain', port=2020): Max retries exceeded with url: /system/info/public (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)')))
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mediaserver.mydomain', port=2020): Max retries exceeded with url: /system/info/public (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/jellyfin_apiclient_python/connection_manager.py", line 156, in connect_to_address
    response_url = self.API.check_redirect(address)
  File "/usr/lib/python3.9/site-packages/jellyfin_apiclient_python/api.py", line 487, in check_redirect
    response = self.send_request(server_address, "system/info/public")
  File "/usr/lib/python3.9/site-packages/jellyfin_apiclient_python/api.py", line 436, in send_request
    return request_method(url, **request_settings)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mediaserver.mydomain', port=2020): Max retries exceeded with url: /system/info/public (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)')))
2021-10-05 09:02:59,209 [   ERROR] JELLYFIN.jellyfin_apiclient_python.connection_manager: connectToAddress https://mediaserver.mydomain:1234 failed
2021-10-05 09:02:59,209 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Trying to login to https://mediaserver.mydomain:1234/Users/AuthenticateByName as JELLOUSER
2021-10-05 09:02:59,209 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending post request to Users/AuthenticateByName
2021-10-05 09:02:59,209 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: (5, 30)
2021-10-05 09:02:59,209 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/json', 'X-Application': 'Jellyfin MPV Shim/2.0.1', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/2.0.1', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=clientcomputer, DeviceId=EEEE-AAAA-ZZZZ-XXXX-DDDD, Version=2.0.1'}
2021-10-05 09:02:59,210 [   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): mediaserver.mydomain:1234
2021-10-05 09:02:59,264 [   ERROR] JELLYFIN.jellyfin_apiclient_python.api: HTTPSConnectionPool(host='mediaserver.mydomain', port=2020): Max retries exceeded with url: /Users/AuthenticateByName (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)')))
2021-10-05 09:02:59,265 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Failed to login as `JELLOUSER`



```

**Comment by mcarlton00** [comment]
The large majority of our clients don't support self signed certs.  You're not going to have a good experience unless you get a signed one from LetsEncrypt or another free provider.

**Comment by aljazzair** [comment]
Closing since this issue has since been reported elsewhere and I am no longer using this app, so can't provide proper follow up.
