### ISSUE TITLE
No package metadata was found for jellyfin-mpv-shim

### ISSUE THREAD

**Issue by DocMAX** [jellyfin/jellyfin-mpv-shim#243]
```
docmax@game: ~ $ jellyfin-mpv-shim 
Traceback (most recent call last):
  File "/usr/bin/jellyfin-mpv-shim", line 33, in <module>
    sys.exit(load_entry_point('jellyfin-mpv-shim==2.0.1', 'console_scripts', 'jellyfin-mpv-shim')())
  File "/usr/bin/jellyfin-mpv-shim", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for jellyfin-mpv-shim

```

**Comment by iwalton3** [comment]
Have any context for this? What distribution are you using, how was it installed, etc.

**Comment by DocMAX** [comment]
Arch Linux. Everything up to date. From AUR (https://aur.archlinux.org/packages/jellyfin-mpv-shim/)

**Comment by iwalton3** [comment]
Looks like there are some comments there that could help. It sounds like you need to reinstall all the python dependencies because of a Python version change.

**Comment by DocMAX** [comment]
Didn't see the comments. Fixed with: yay -S --answerclean All ds4drv ffpb jellyfin-mpv-shim lutris-git mugshot python-jellyfin-apiclient python-mpv python-py3nvml python-pystray
