### ISSUE TITLE
mpv closes, but jellyfin still says I am playing a video

### ISSUE THREAD

**Issue by beari22** [jellyfin/jellyfin-mpv-shim#259]
**Describe the bug**
i close mpv, jellyfin still shows playing
this only happens if i on `always_transcode` 
and i am useing a external player

Attention! Please be sure to avoid posting any API keys. I don't want other people to be able to compromise your server! : ok
API Keys are now removed from logs by default, but they may still appear in other places, such as on MPV info screens.

**To Reproduce**
1. on `always_transcode` in config.json
2. go to a mpv client and connect mpv-shim
3. play a video in jellyfin
4. then close mpv player

**Expected behavior**
the playing thing goes away

**Screenshots**
![image](https://user-images.githubusercontent.com/91468081/166063734-ce46d88d-971e-4ccf-970f-193faa959e85.png)

![image](https://user-images.githubusercontent.com/91468081/166063748-d1afdbdc-2942-4846-a257-29155df961d3.png)

**Desktop (please complete the following information):**
 - OS: Windows 21H1
 - Version: 2.0.2
 - External Mpv Version: 0.34.0 

**Error Messages**
```
====THE ERROR====
2022-04-29 23:48:59,540 [   ERROR] mpv-jsonipc: EventHandler caught exception from (<function PlayerManager.__init__.<locals>.handle_stop at 0x00000238FB40EE58>, ()).
Traceback (most recent call last):
  File "jellyfin_apiclient_python\http.py", line 121, in request
  File "requests\models.py", line 953, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://{RemoteHost}/{UserName}/jellyfin/Videos/ActiveEncodings?DeviceId={this looked importent so i removed it}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python_mpv_jsonipc.py", line 370, in run
  File "jellyfin_mpv_shim\player.py", line 213, in handle_stop
  File "jellyfin_mpv_shim\utils.py", line 54, in _synchronizer
  File "jellyfin_mpv_shim\player.py", line 531, in stop
  File "jellyfin_mpv_shim\media.py", line 151, in terminate_transcode
  File "jellyfin_apiclient_python\api.py", line 423, in close_transcode
  File "jellyfin_apiclient_python\api.py", line 73, in _delete
  File "jellyfin_apiclient_python\api.py", line 51, in _http
  File "jellyfin_apiclient_python\http.py", line 176, in request
jellyfin_apiclient_python.exceptions.HTTPException: (400, HTTPError('400 Client Error: Bad Request for url: /https://{RemoteHost}/{UserName}/jellyfin/Videos/ActiveEncodings?DeviceId={this looked importent so i removed it}'))
2022-04-29 23:48:59,544 [    INFO] mpv: cplayer:
=================
```

> Note: whenever this happens there are extra `run.exe` in task manager

**Comment by beari22** [comment]
===MY CONFIG===
```json
{
    "always_transcode": true,
    "audio_output": "hdmi",
    "auto_play": false,
    "check_updates": true,
    "client_uuid": "{this looked important}",
    "connect_retry_mins": 0,
    "direct_paths": false,
    "discord_presence": false,
    "display_mirroring": false,
    "enable_gui": true,
    "enable_osc": false,
    "fullscreen": false,
    "idle_cmd": null,
    "idle_cmd_delay": 60,
    "idle_when_paused": false,
    "ignore_ssl_cert": false,
    "kb_debug": "~",
    "kb_fullscreen": "f",
    "kb_kill_shader": "k",
    "kb_menu": "c",
    "kb_menu_down": "down",
    "kb_menu_esc": "esc",
    "kb_menu_left": "left",
    "kb_menu_ok": "enter",
    "kb_menu_right": "right",
    "kb_menu_up": "up",
    "kb_next": ">",
    "kb_pause": "space",
    "kb_prev": "<",
    "kb_stop": "q",
    "kb_unwatched": "u",
    "kb_watched": "w",
    "lang": null,
    "lang_filter": "und,eng,jpn,mis,mul,zxx",
    "lang_filter_audio": false,
    "lang_filter_sub": false,
    "local_kbps": 2147483,
    "log_decisions": false,
    "media_ended_cmd": null,
    "media_key_seek": false,
    "media_keys": true,
    "menu_mouse": true,
    "mpv_ext": true,
    "mpv_ext_ipc": null,
    "mpv_ext_no_ovr": true,
    "mpv_ext_path": "C:\\ProgramData\\chocolatey\\lib\\mpv.install\\tools\\mpv.exe",
    "mpv_ext_start": true,
    "mpv_log_level": "info",
    "notify_updates": true,
    "playback_timeout": 30,
    "player_name": "beari",
    "pre_media_cmd": null,
    "remote_direct_paths": false,
    "remote_kbps": 10000,
    "sanitize_output": true,
    "screenshot_dir": "C:\\Users\\Me\\Desktop",
    "screenshot_menu": true,
    "seek_down": -60,
    "seek_h_exact": false,
    "seek_left": -5,
    "seek_right": 5,
    "seek_up": 60,
    "seek_v_exact": false,
    "shader_pack_custom": false,
    "shader_pack_enable": false,
    "shader_pack_profile": null,
    "shader_pack_remember": true,
    "stop_cmd": null,
    "stop_idle": false,
    "subtitle_color": "#FFFFFFFF",
    "subtitle_position": "bottom",
    "subtitle_size": 100,
    "svp_enable": false,
    "svp_socket": null,
    "svp_url": "http://127.0.0.1:9901/",
    "sync_attempts": 5,
    "sync_max_delay_skip": 300,
    "sync_max_delay_speed": 50,
    "sync_method_thresh": 2000,
    "sync_osd_message": true,
    "sync_revert_seek": true,
    "sync_speed_attempts": 3,
    "sync_speed_time": 1000,
    "transcode_h265": true,
    "transcode_hi10p": true,
    "transcode_to_h265": false,
    "transcode_warning": false,
    "use_web_seek": false,
    "write_logs": true
}
```
======

**Comment by beari22** [comment]
come to think of it i might have a old vr. of mpv-shim
i will try to redownload mpv-shim

**Comment by beari22** [comment]
nope i have 2.0.2

**Comment by karserasl** [comment]
It might not be the same problem, but i saw the same behavior when i had no-border in mpv.conf.

**Comment by iwalton3** [comment]
Is this happening consistently? The exception in the log is because the server threw an error when it tried to terminate a media transcode.

I wonder if it is remuxing so it doesn't actually have a transcode to terminate...

**Comment by iwalton3** [comment]
I added change that will make it so that if a transcode fails to terminate it doesn't kill the UI. Now if you do have lingering transcodes after the player tries to terminate them, you may want to open a bug against the server.
