### ISSUE TITLE
Many non-fatal type errors after pausing or doing something in mpv

### ISSUE THREAD

**Issue by Dabbing-Guy** [jellyfin/jellyfin-mpv-shim#267]
**Describe the bug**
The console log of the program while watching 

**To Reproduce**
1. Cast to a computer running `jellyfin-mpv-shim` in a terminal
2. Watch for a bit
3. Pause the media
4. Wait a little bit
5. See errors 

**Expected behavior**
No errors when pausing

**Desktop (please complete the following information):**
 - OS: Bedrock Linux
 - Using `jellyfin-mpv-shim` from PyPI installed with `doas pip install jellyfin-mpv-shim`
 - Python 3.10.5 from Artix repo

**Error Messages**

The console output (the server url and port have been replaced with `serverurl`: 
```
2022-06-08 16:10:14,251 [ WARNING] player: Error when processing client-message.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 379, in handle_client_message
    if "event_id" in event:
TypeError: argument of type 'MpvEvent' is not iterable
2022-06-08 16:10:14,273 [ WARNING] player: Error when processing client-message.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 379, in handle_client_message
    if "event_id" in event:
TypeError: argument of type 'MpvEvent' is not iterable
2022-06-08 16:10:14,488 [ WARNING] player: Error when processing client-message.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 379, in handle_client_message
    if "event_id" in event:
TypeError: argument of type 'MpvEvent' is not iterable
2022-06-08 16:10:20,981 [   DEBUG] urllib3.connectionpool: serverurl "POST /Sessions/Playing/Progress HTTP/1.1" 204 0
2022-06-08 16:10:27,125 [   DEBUG] urllib3.connectionpool: serverurl "POST /Sessions/Playing/Progress HTTP/1.1" 204 0
2022-06-08 16:10:34,987 [ WARNING] player: Error when processing client-message.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 379, in handle_client_message
    if "event_id" in event:
TypeError: argument of type 'MpvEvent' is not iterable
2022-06-08 16:10:35,069 [ WARNING] player: Error when processing client-message.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 379, in handle_client_message
    if "event_id" in event:
TypeError: argument of type 'MpvEvent' is not iterable
2022-06-08 16:10:35,093 [ WARNING] player: Error when processing client-message.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 379, in handle_client_message
    if "event_id" in event:
TypeError: argument of type 'MpvEvent' is not iterable
2022-06-08 16:10:35,125 [ WARNING] player: Error when processing client-message.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 379, in handle_client_message
    if "event_id" in event:
TypeError: argument of type 'MpvEvent' is not iterable
2022-06-08 16:10:35,166 [ WARNING] player: Error when processing client-message.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 379, in handle_client_message
    if "event_id" in event:
TypeError: argument of type 'MpvEvent' is not iterable
2022-06-08 16:10:35,221 [ WARNING] player: Error when processing client-message.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 379, in handle_client_message
    if "event_id" in event:
TypeError: argument of type 'MpvEvent' is not iterable
2022-06-08 16:10:37,856 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: KeepAlive received from server.
```

**Comment by iwalton3** [comment]
Fixed in https://github.com/jellyfin/jellyfin-mpv-shim/commit/e360e07d1a6f0d3e2210d60a77bd6874041df0c2

**Comment by Dabbing-Guy** [comment]
You guys should really make another release and push it to PyPI then

**Comment by iwalton3** [comment]
I’m waiting for the next stable release but that has been “this weekend” for weeks now. I’ll probably just bite the bullet and do a release since this is likely breaking things for more users as this gets updated.
