### ISSUE TITLE
Can't start shim on a fresh install from pip (Linux Mint)

### ISSUE THREAD

**Issue by clearedTakeoff** [jellyfin/jellyfin-mpv-shim#292]
**Describe the bug**
After installing jellyfin-mpv-shim using pip I'm unable to start it at all. Not sure if I'm using wrong Python version or there's something else messing up here. I am using plex-mpv-shim on the same system if there are any potential conflicts? 

**To Reproduce**
1. Install jellyfin-mpv-shim using pip (python 3.8): `sudo pip3 install --upgrade jellyfin-mpv-shim`*
2. Run `jellyfin-mpv-shim` in terminal
3. See error

\* Note: I also tried installing the remaining (optional) libraries just in case that would help (it didn't)
```
sudo pip3 install pystray
sudo apt install python3-tk
sudo apt install python3-jinja2 python3-webview
sudo pip3 install jellyfin-mpv-shim[discord]
```

**Expected behavior**
jellyfin-mpv-shim should start without any error.

**Desktop (please complete the following information):**
 - OS: Linux Mint Cinnamon
 - Version: 20.1
 - Python: 3.8

**Error Messages**
```
Traceback (most recent call last):
  File "/usr/local/bin/jellyfin-mpv-shim", line 5, in <module>
    from jellyfin_mpv_shim.mpv_shim import main
  File "/usr/local/lib/python3.8/dist-packages/jellyfin_mpv_shim/mpv_shim.py", line 11, in <module>
    from .clients import clientManager
  File "/usr/local/lib/python3.8/dist-packages/jellyfin_mpv_shim/clients.py", line 1, in <module>
    from jellyfin_apiclient_python import JellyfinClient
  File "/usr/local/lib/python3.8/dist-packages/jellyfin_apiclient_python/__init__.py", line 8, in <module>
    from .client import JellyfinClient
  File "/usr/local/lib/python3.8/dist-packages/jellyfin_apiclient_python/client.py", line 8, in <module>
    from . import api
  File "/usr/local/lib/python3.8/dist-packages/jellyfin_apiclient_python/api.py", line 38, in <module>
    class API(object):
  File "/usr/local/lib/python3.8/dist-packages/jellyfin_apiclient_python/api.py", line 426, in API
    self, id: str, item_ids: list[str], command: str = "PlayNow", params={}, json={}
TypeError: 'type' object is not subscriptable
```
\
Installing using flatpak kind of works: I can configure my server but nothing plays. I'm including this since it seems that in both cases I'm having an issue with API client (though they might be unrelated). Jellyfin version is 10.8.0
```
2022-08-24 22:59:38,978 [   DEBUG] event_handler: Handled Event Play: {'ItemIds': ['9a32f23458bc1bb62560e27ff9e2b6b7'], 'PlayCommand': 'PlayNow', 'ControllingUserId': 'baaef3d29275456cbab15589a50fb6c6', 'ServerId': 'de51300f27bc477f9126383837b3d11a'}
2022-08-24 22:59:38,985 [   DEBUG] urllib3.connectionpool: Resetting dropped connection: redacted
2022-08-24 22:59:39,199 [   DEBUG] urllib3.connectionpool: http://redacted:80 "GET /jellyfin/Users/baaef3d29275456cbab15589a50fb6c6/Items/9a32f23458bc1bb62560e27ff9e2b6b7 HTTP/1.1" 200 None
2022-08-24 22:59:39,334 [   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): checkip.amazonaws.com:443
2022-08-24 22:59:39,780 [   DEBUG] urllib3.connectionpool: https://checkip.amazonaws.com:443 "GET / HTTP/1.1" 200 15
2022-08-24 22:59:39,787 [   DEBUG] charset_normalizer: Encoding detection: ascii is most likely the one.
2022-08-24 22:59:39,787 [   DEBUG] event_handler: EventHandler::playMedia <jellyfin_mpv_shim.media.Media object at 0x7f9398410fd0>
2022-08-24 22:59:39,788 [   DEBUG] media: Bandwidth: local=False, bitrate=None, force=False
2022-08-24 22:59:40,044 [   DEBUG] urllib3.connectionpool: http://redacted:80 "POST /jellyfin/Items/9a32f23458bc1bb62560e27ff9e2b6b7/PlaybackInfo HTTP/1.1" 200 None
2022-08-24 22:59:40,047 [   ERROR] websocket: error from callback <function WSClient.run.<locals>.<lambda> at 0x7f939ad44ee0>: 'NoneType' object has no attribute 'get'
2022-08-24 22:59:40,048 [   ERROR] JELLYFIN.jellyfin_apiclient_python.ws_client: 'NoneType' object has no attribute 'get'
2022-08-24 22:59:40,049 [   DEBUG] event_handler: Unhandled Event WebSocketError: 'NoneType' object has no attribute 'get'

**Comment by iwalton3** [comment]
Should be fixed now. Let me know if it isn't.
