### ISSUE TITLE
`getaddrinfo` fails for system/info/public

### ISSUE THREAD

**Issue by rhetr** [jellyfin/jellyfin-mpv-shim#298]
**Describe the bug**
i've been using jellyfin mpv shim for a while with `"ignore_ssl_cert": true` on a jellyfin server running behind a traefik reverse proxy. recently i had to take my server down and set it back up. after I did I was no longer able to connect with jellyfin mpv shim even though I am able to access jellyfin through a browser. I tried:

- removing and readding the server
- using links with https://, http:// and neither
- uninstalling 2.0.2 and installing 2.2.0

but there is no difference. I also noticed whenever I quit jellyfin mpv shim there is still 1 remaining `run` process that I see in Task Manager, not sure if that's related. might be because i set `"connect_retry_mins": 1`

**To Reproduce**
1. input server details and attempt to connect

i was also able to access 'https://jelly.baku.lan/system/info/public' from multiple computers' browsers, and i was able to successfully run the following python code on multiple computers:

```python
import socket
socket.getaddrinfo('jelly.baku.lan', 443)
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 2.0.2 and 2.2.0

**Error Messages**
```
2022-09-15 11:58:34,106 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.client: JellyfinClient initializing...
2022-09-15 11:58:34,106 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Configuration initializing...
2022-09-15 11:58:34,106 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin http constructor.
2022-09-15 11:58:34,106 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: WSClient initializing...
2022-09-15 11:58:34,106 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: ConnectionManager initializing...
2022-09-15 11:58:34,106 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: Credentials initializing...
2022-09-15 11:58:34,106 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin app constructor.
2022-09-15 11:58:34,107 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2022-09-15 11:58:34,107 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2022-09-15 11:58:34,107 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 'X-Application': 'Jellyfin MPV Shim/2.2.0', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/2.2.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=DANAE, DeviceId=b35a8d55-ee86-446f-affe-e8b19d941ea0, Version=2.2.0'}
2022-09-15 11:58:34,107 [   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): jelly.baku.lan:443
2022-09-15 11:58:34,161 [   DEBUG] urllib3.connectionpool: https://jelly.baku.lan:443 "GET /system/info/public HTTP/1.1" 200 None
2022-09-15 11:58:34,161 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connectToAddress https://jelly.baku.lan succeeded
2022-09-15 11:58:34,161 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connectToServer
2022-09-15 11:58:34,161 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2022-09-15 11:58:34,162 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2022-09-15 11:58:34,162 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 'X-Application': 'Jellyfin MPV Shim/2.2.0', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/2.2.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=DANAE, DeviceId=b35a8d55-ee86-446f-affe-e8b19d941ea0, Version=2.2.0'}
2022-09-15 11:58:34,162 [   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): jelly.baku.lan:443
2022-09-15 11:58:34,163 [   ERROR] JELLYFIN.jellyfin_apiclient_python.connection_manager: Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 72, in create_connection
  File "socket.py", line 954, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1040, in _validate_conn
  File "urllib3\connection.py", line 358, in connect
  File "urllib3\connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000017B93CCB2B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jelly.baku.lan', port=443): Max retries exceeded with url: /system/info/public (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B93CCB2B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jellyfin_apiclient_python\connection_manager.py", line 180, in connect_to_server
  File "jellyfin_apiclient_python\api.py", line 513, in get_public_info
  File "jellyfin_apiclient_python\api.py", line 469, in send_request
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 565, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='jelly.baku.lan', port=443): Max retries exceeded with url: /system/info/public (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B93CCB2B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

2022-09-15 11:58:34,164 [   ERROR] JELLYFIN.jellyfin_apiclient_python.connection_manager: Failing server connection. ERROR msg: HTTPSConnectionPool(host='jelly.baku.lan', port=443): Max retries exceeded with url: /system/info/public (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B93CCB2B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-09-15 11:58:34,164 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Trying to login to https://jelly.baku.lan/Users/AuthenticateByName as pert
2022-09-15 11:58:34,164 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending post request to Users/AuthenticateByName
2022-09-15 11:58:34,164 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: (5, 30)
2022-09-15 11:58:34,164 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/json', 'X-Application': 'Jellyfin MPV Shim/2.2.0', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/2.2.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=DANAE, DeviceId=b35a8d55-ee86-446f-affe-e8b19d941ea0, Version=2.2.0'}
2022-09-15 11:58:34,164 [   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): jelly.baku.lan:443
2022-09-15 11:58:34,164 [   ERROR] JELLYFIN.jellyfin_apiclient_python.api: HTTPSConnectionPool(host='jelly.baku.lan', port=443): Max retries exceeded with url: /Users/AuthenticateByName (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B93CCB040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-09-15 11:58:34,165 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Failed to login as `pert`
```

**Comment by rhetr** [comment]
also i can access the same server with a different computer running macos
