### ISSUE TITLE
Crashed on starting (Unhandled exception in script)

### ISSUE THREAD

**Issue by slikas** [jellyfin/jellyfin-mpv-shim#305]
Installed, started the app then it crashed.
The log:

```
Traceback (most recent call last):
  File "run.py", line 23, in <module>
  File "jellyfin_mpv_shim\mpv_shim.py", line 65, in main
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "jellyfin_mpv_shim\player.py", line 1033, in <module>
  File "jellyfin_mpv_shim\player.py", line 173, in __init__
  File "python_mpv_jsonipc.py", line 418, in __init__
  File "python_mpv_jsonipc.py", line 224, in __init__
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by iwalton3** [comment]
`python_mpv_jsonipc` shouldn't be used by default on the Windows version. Have you changed any configurations?
