### ISSUE TITLE
Discord RPC sending empty state

### ISSUE THREAD

**Issue by LividJava** [jellyfin/jellyfin-mpv-shim#310]
**Describe the bug**
Discord Rich Presence fails to post because State is empty

**To Reproduce**
Uncertain of reproduction.

1. Ensure discord-rpc is enabled in the config
2. launch jellyfin-mpv-shim
3. Obtain error code 4000.
`pypresence.exceptions.DiscordError: Error Code: 4000 Message: child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]]`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Endeavour Rolling
 - Version 2.2.0

**Error Messages**
<details>

<summary>Error Log</summary>

```
2023-01-28 03:39:40,595 [   DEBUG] asyncio: Using selector: EpollSelector
2023-01-28 03:39:40,949 [    INFO] player: Using external mpv playback backend.
2023-01-28 03:39:40,950 [   DEBUG] mpv-jsonipc: Staring MPV from mpv.
2023-01-28 03:39:40,950 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv236909024627881 for MPV.
2023-01-28 03:39:41,051 [   DEBUG] mpv-jsonipc: Found MPV socket.
2023-01-28 03:39:41,060 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.client: JellyfinClient initializing...
2023-01-28 03:39:41,060 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Configuration initializing...
2023-01-28 03:39:41,060 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin http constructor.
2023-01-28 03:39:41,060 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: WSClient initializing...
2023-01-28 03:39:41,060 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: ConnectionManager initializing...
2023-01-28 03:39:41,060 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: Credentials initializing...
2023-01-28 03:39:41,061 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin app constructor.
2023-01-28 03:39:41,061 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin connect
2023-01-28 03:39:41,061 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin getAvailableServers
2023-01-28 03:39:41,061 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: credentialsupdated
2023-01-28 03:39:41,061 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connect has 1 servers
2023-01-28 03:39:41,061 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connect_to_server
2023-01-28 03:39:41,061 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2023-01-28 03:39:41,062 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2023-01-28 03:39:41,062 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 'X-Application': 'Jellyfin MPV Shim/2.2.0', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/2.2.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=Aliza, DeviceId=24f0fb9c-280f-4687-be6c-0816d55c231c, Version=2.2.0'}
2023-01-28 03:39:41,064 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 192.168.1.128:8096
2023-01-28 03:39:41,067 [   DEBUG] urllib3.connectionpool: http://192.168.1.128:8096 "GET /system/info/public HTTP/1.1" 200 None
2023-01-28 03:39:41,069 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: calling onSuccessfulConnection with server lvdsrv0802
2023-01-28 03:39:41,069 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info
2023-01-28 03:39:41,069 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2023-01-28 03:39:41,069 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 'X-Application': 'Jellyfin MPV Shim/2.2.0', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/2.2.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=Aliza, DeviceId=24f0fb9c-280f-4687-be6c-0816d55c231c, Version=2.2.0', 'X-MediaBrowser-Token': 'REDACTED'}
2023-01-28 03:39:41,070 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 192.168.1.128:8096
2023-01-28 03:39:41,076 [   DEBUG] urllib3.connectionpool: http://192.168.1.128:8096 "GET /system/info HTTP/1.1" 200 None
2023-01-28 03:39:41,079 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: credentialsupdated
2023-01-28 03:39:41,079 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: resolving connect with result: {'Servers': "[{'address': 'http://192.168.1.128:8096', 'Name': 'lvdsrv0802', 'Id': 'f5a626c853d9434390a4c1a9a3a18681', 'DateLastAccessed': '2023-01-28T03:39:41Z', 'UserId': '7fcc6daadc064774a8d91689b244cb07', 'AccessToken': 'REDACTED', 'Users': [{'Id': '7fcc6daadc064774a8d91689b244cb07', 'IsSignedInOffline': True}], 'uuid': '84b9991e-5fd0-4f90-91bb-98f4ea40f5b0', 'username': 'lividjava', 'connected': True}]", 'State': 3}
2023-01-28 03:39:41,079 [    INFO] JELLYFIN.jellyfin_apiclient_python.client: User is authenticated.
2023-01-28 03:39:41,079 [   DEBUG] urllib3.util.retry: Converted retries value: 3 -> 'Retry(total=3, connect=None, read=None, redirect=None, status=None)'
2023-01-28 03:39:41,079 [   DEBUG] urllib3.util.retry: Converted retries value: 3 -> 'Retry(total=3, connect=None, read=None, redirect=None, status=None)'
2023-01-28 03:39:41,079 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: Websocket url: ws://192.168.1.128:8096/socket?api_key=REDACTEDREDACTED&device_id=24f0fb9c-280f-4687-be6c-0816d55c231c
2023-01-28 03:39:41,080 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 192.168.1.128:8096
2023-01-28 03:39:41,109 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: --->[ websocket ]
2023-01-28 03:39:41,110 [   DEBUG] event_handler: Unhandled Event WebSocketConnect: None
2023-01-28 03:39:41,110 [ WARNING] websocket: websocket connected
2023-01-28 03:39:41,121 [   DEBUG] urllib3.connectionpool: http://192.168.1.128:8096 "POST /Sessions/Capabilities/Full HTTP/1.1" 204 0
2023-01-28 03:39:41,127 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: ForceKeepAlive received from server.
2023-01-28 03:39:41,135 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: KeepAlive received from server.
2023-01-28 03:39:41,146 [   DEBUG] urllib3.connectionpool: http://192.168.1.128:8096 "GET /Sessions?ControllableByUserId=7fcc6daadc064774a8d91689b244cb07 HTTP/1.1" 200 None
2023-01-28 03:39:41,177 [   DEBUG] PIL.PngImagePlugin: STREAM "b'IHDR'" 16 13
2023-01-28 03:39:41,177 [   DEBUG] PIL.PngImagePlugin: STREAM "b'pHYs'" 41 9
2023-01-28 03:39:41,178 [   DEBUG] PIL.PngImagePlugin: STREAM "b'IDAT'" 62 709
2023-01-28 03:39:52,234 [   DEBUG] event_handler: Handled Event Play: {'ItemIds': ['6eb083a32200c99b39e45e74cc0be3c4', 'e5a3471d165bb3e8a535983d5e0690e9', '429c71fa2495bdf4dad6746aa88dbcba', '6a22e8922036432cb21d7b6c8af22e42', '28620b90e02495ac67299054489faf09', '7d5a8384b8dbdc4f4b6b8f55a870e1f3', '682aa870f4132c5b5612d70ecedac6de', 'e64cd9d169ce65027b882a6f2bca33ca', '6e046a82dd70148f4c416da3e579d2fd', '2b94b782a7e8bc1d9e15e2007cd61095'], 'PlayCommand': 'PlayNow', 'ControllingUserId': '7fcc6daadc064774a8d91689b244cb07', 'StartIndex': 8, 'ServerId': 'f5a626c853d9434390a4c1a9a3a18681'}
2023-01-28 03:39:52,249 [   DEBUG] urllib3.connectionpool: http://192.168.1.128:8096 "GET /Users/7fcc6daadc064774a8d91689b244cb07/Items/6e046a82dd70148f4c416da3e579d2fd HTTP/1.1" 200 None
2023-01-28 03:39:52,252 [   DEBUG] event_handler: EventHandler::playMedia <jellyfin_mpv_shim.media.Media object at 0x7f0e04305150>
2023-01-28 03:39:52,252 [   DEBUG] media: Bandwidth: local=True, bitrate=None, force=False
2023-01-28 03:39:52,271 [   DEBUG] urllib3.connectionpool: http://192.168.1.128:8096 "POST /Items/6e046a82dd70148f4c416da3e579d2fd/PlaybackInfo HTTP/1.1" 200 None
2023-01-28 03:39:52,272 [   DEBUG] media: Using direct url.
2023-01-28 03:39:52,317 [    INFO] mpv: cplayer: (+) Audio --aid=1 (pcm_s16le 2ch 48000Hz)
2023-01-28 03:39:52,318 [   DEBUG] player: Finished waiting for media duration.
2023-01-28 03:39:52,323 [    INFO] mpv: cplayer: AO: [pipewire] 48000Hz stereo 2ch s16
2023-01-28 03:39:52,325 [   DEBUG] player: PlayerManager::play selecting subtitle stream (none)
2023-01-28 03:39:52,327 [    INFO] mpv: cplayer: Track switched:
2023-01-28 03:39:52,327 [    INFO] mpv: cplayer: (+) Audio --aid=1 (pcm_s16le 2ch 48000Hz)
2023-01-28 03:39:52,335 [   ERROR] asyncio: Fatal error: protocol.data_received() call failed.
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7f0e04c1df60>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 876, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/lib/python3.10/asyncio/streams.py", line 266, in data_received
    reader.feed_data(data)
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 68, in on_event
    raise DiscordError(payload["data"]["code"], payload["data"]["message"])
pypresence.exceptions.DiscordError: Error Code: 4000 Message: child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]]
2023-01-28 03:39:52,336 [   ERROR] player: Could not send Discord Rich Presence.
Traceback (most recent call last):
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 870, in get_timeline_options
    send_presence(
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/rich_presence.py", line 27, in send_presence
    RPC.set_activity(
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 138, in set_activity
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 88, in read_output
    raise ServerError(payload["data"]["message"])
pypresence.exceptions.ServerError: Child "activity" fails because child "state" fails because "state" is not allowed to be empty
2023-01-28 03:39:52,584 [   DEBUG] urllib3.connectionpool: http://192.168.1.128:8096 "POST /Sessions/Playing HTTP/1.1" 204 0
2023-01-28 03:39:52,585 [    INFO] update_check: Checking for updates...
2023-01-28 03:39:52,586 [   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): github.com:443
2023-01-28 03:39:52,840 [   DEBUG] urllib3.connectionpool: https://github.com:443 "GET /jellyfin/jellyfin-mpv-shim/releases/latest HTTP/1.1" 302 0
2023-01-28 03:39:52,843 [   ERROR] player: Could not send Discord Rich Presence.
Traceback (most recent call last):
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 870, in get_timeline_options
    send_presence(
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/rich_presence.py", line 27, in send_presence
    RPC.set_activity(
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 138, in set_activity
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 81, in read_output
    preamble = await self.sock_reader.read(8)
  File "/usr/lib/python3.10/asyncio/streams.py", line 649, in read
    raise self._exception
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 876, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/lib/python3.10/asyncio/streams.py", line 266, in data_received
    reader.feed_data(data)
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 68, in on_event
    raise DiscordError(payload["data"]["code"], payload["data"]["message"])
pypresence.exceptions.DiscordError: Error Code: 4000 Message: child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]]
2023-01-28 03:39:52,911 [   DEBUG] urllib3.connectionpool: http://192.168.1.128:8096 "POST /Sessions/Playing/Progress HTTP/1.1" 204 0
2023-01-28 03:39:52,994 [   DEBUG] event_handler: Unhandled Event UserDataChanged: {'UserId': '7fcc6daadc064774a8d91689b244cb07', 'UserDataList': [{'PlaybackPositionTicks': 0, 'PlayCount': 2, 'IsFavorite': False, 'LastPlayedDate': '2023-01-28T08:39:52.3685296Z', 'Played': True, 'Key': 'surreal sippin', 'ItemId': '6e046a82dd70148f4c416da3e579d2fd'}, {'PlaybackPositionTicks': 0, 'PlayCount': 0, 'IsFavorite': False, 'Played': False, 'Key': 'd9e3380b-b941-e237-128f-ab8d28a0d4c6', 'ItemId': 'd9e3380bb941e237128fab8d28a0d4c6'}], 'ServerId': 'f5a626c853d9434390a4c1a9a3a18681'}
2023-01-28 03:39:57,586 [   ERROR] player: Could not send Discord Rich Presence.
Traceback (most recent call last):
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 870, in get_timeline_options
    send_presence(
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/rich_presence.py", line 27, in send_presence
    RPC.set_activity(
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 138, in set_activity
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 81, in read_output
    preamble = await self.sock_reader.read(8)
  File "/usr/lib/python3.10/asyncio/streams.py", line 649, in read
    raise self._exception
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 870, in get_timeline_options
    send_presence(
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/rich_presence.py", line 27, in send_presence
    RPC.set_activity(
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 138, in set_activity
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 81, in read_output
    preamble = await self.sock_reader.read(8)
  File "/usr/lib/python3.10/asyncio/streams.py", line 649, in read
    raise self._exception
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 876, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/lib/python3.10/asyncio/streams.py", line 266, in data_received
    reader.feed_data(data)
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 68, in on_event
    raise DiscordError(payload["data"]["code"], payload["data"]["message"])
pypresence.exceptions.DiscordError: Error Code: 4000 Message: child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]]
2023-01-28 03:39:57,700 [   DEBUG] urllib3.connectionpool: http://192.168.1.128:8096 "POST /Sessions/Playing/Progress HTTP/1.1" 204 0
2023-01-28 03:40:00,070 [   DEBUG] event_handler: Handled Event Playstate: {'Command': 'Stop', 'ControllingUserId': '7fcc6daadc064774a8d91689b244cb07', 'ServerId': 'f5a626c853d9434390a4c1a9a3a18681'}
2023-01-28 03:40:00,071 [   DEBUG] player: PlayerManager::stop stopping playback of <jellyfin_mpv_shim.media.Video object at 0x7f0e04304d90>
2023-01-28 03:40:00,072 [   ERROR] player: Could not send Discord Rich Presence.
Traceback (most recent call last):
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 870, in get_timeline_options
    send_presence(
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/rich_presence.py", line 27, in send_presence
    RPC.set_activity(
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 138, in set_activity
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 81, in read_output
    preamble = await self.sock_reader.read(8)
  File "/usr/lib/python3.10/asyncio/streams.py", line 649, in read
    raise self._exception
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 870, in get_timeline_options
    send_presence(
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/rich_presence.py", line 27, in send_presence
    RPC.set_activity(
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 138, in set_activity
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 81, in read_output
    preamble = await self.sock_reader.read(8)
  File "/usr/lib/python3.10/asyncio/streams.py", line 649, in read
    raise self._exception
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 870, in get_timeline_options
    send_presence(
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/rich_presence.py", line 27, in send_presence
    RPC.set_activity(
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 138, in set_activity
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 81, in read_output
    preamble = await self.sock_reader.read(8)
  File "/usr/lib/python3.10/asyncio/streams.py", line 649, in read
    raise self._exception
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 876, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/lib/python3.10/asyncio/streams.py", line 266, in data_received
    reader.feed_data(data)
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 68, in on_event
    raise DiscordError(payload["data"]["code"], payload["data"]["message"])
pypresence.exceptions.DiscordError: Error Code: 4000 Message: child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]]
2023-01-28 03:40:00,084 [    INFO] mpv: cplayer: 
2023-01-28 03:40:00,312 [   DEBUG] urllib3.connectionpool: http://192.168.1.128:8096 "POST /Sessions/Playing/Stopped HTTP/1.1" 204 0
2023-01-28 03:40:00,313 [   ERROR] player: Could not clear Discord Rich Presence.
Traceback (most recent call last):
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 917, in send_timeline_stopped
    clear_presence()
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/rich_presence.py", line 43, in clear_presence
    RPC.clear_activity()
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 143, in clear_activity
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 81, in read_output
    preamble = await self.sock_reader.read(8)
  File "/usr/lib/python3.10/asyncio/streams.py", line 649, in read
    raise self._exception
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 870, in get_timeline_options
    send_presence(
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/rich_presence.py", line 27, in send_presence
    RPC.set_activity(
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 138, in set_activity
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 81, in read_output
    preamble = await self.sock_reader.read(8)
  File "/usr/lib/python3.10/asyncio/streams.py", line 649, in read
    raise self._exception
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 870, in get_timeline_options
    send_presence(
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/rich_presence.py", line 27, in send_presence
    RPC.set_activity(
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 138, in set_activity
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 81, in read_output
    preamble = await self.sock_reader.read(8)
  File "/usr/lib/python3.10/asyncio/streams.py", line 649, in read
    raise self._exception
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/player.py", line 870, in get_timeline_options
    send_presence(
  File "/home/lividjava/.local/lib/python3.10/site-packages/jellyfin_mpv_shim/rich_presence.py", line 27, in send_presence
    RPC.set_activity(
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 138, in set_activity
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 81, in read_output
    preamble = await self.sock_reader.read(8)
  File "/usr/lib/python3.10/asyncio/streams.py", line 649, in read
    raise self._exception
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 876, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/lib/python3.10/asyncio/streams.py", line 266, in data_received
    reader.feed_data(data)
  File "/home/lividjava/.local/lib/python3.10/site-packages/pypresence/client.py", line 68, in on_event
    raise DiscordError(payload["data"]["code"], payload["data"]["message"])
pypresence.exceptions.DiscordError: Error Code: 4000 Message: child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]]
2023-01-28 03:40:00,798 [   DEBUG] event_handler: Unhandled Event UserDataChanged: {'UserId': '7fcc6daadc064774a8d91689b244cb07', 'UserDataList': [{'PlaybackPositionTicks': 0, 'PlayCount': 2, 'IsFavorite': False, 'LastPlayedDate': '2023-01-28T08:39:52.3685296Z', 'Played': True, 'Key': 'surreal sippin', 'ItemId': '6e046a82dd70148f4c416da3e579d2fd'}, {'PlaybackPositionTicks': 0, 'PlayCount': 0, 'IsFavorite': False, 'Played': False, 'Key': 'd9e3380b-b941-e237-128f-ab8d28a0d4c6', 'ItemId': 'd9e3380bb941e237128fab8d28a0d4c6'}], 'ServerId': 'f5a626c853d9434390a4c1a9a3a18681'}
2023-01-28 03:40:06,405 [    INFO] root: Stopping services...
2023-01-28 03:40:08,103 [    INFO] Jellyfin.jellyfin_apiclient_python.http: --<[ session/139698176194736 ]
2023-01-28 03:40:08,104 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: ---<[ websocket ]
```

</details>

**Comment by iwalton3** [comment]
Looks like this is because the title of whatever you were watching was empty. I have updated it to say "Unknown Media" if this is the case as well as clean up the status a bit.
