### ISSUE TITLE
Discord RPC Broken

### ISSUE THREAD

**Issue by lewisakura** [jellyfin/jellyfin-mpv-shim#334]
**Describe the bug**
Discord rich presense no longer works, and the logs indicate that the application used to serve rich presence has been deleted or is just incorrect.

**To Reproduce**
1. Enable Discord Rich Presence
2. Look in the logs

**Expected behavior**
Rich presence works.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version [e.g. 1.2.0] 2.6.0

**Error Messages**
Please provide logs, as they are often needed for me to understand and quickly troubleshoot the issue. You can read instructions for how to do so here:
https://github.com/iwalton3/jellyfin-mpv-shim/wiki/Sending-Logs

```
-snip, repeating of the two lines below-
  File "pypresence\baseclient.py", line 81, in read_output
  File "asyncio\streams.py", line 665, in read
  File "asyncio\proactor_events.py", line 395, in _loop_writing
  File "asyncio\windows_events.py", line 539, in send
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jellyfin_mpv_shim\player.py", line 1016, in send_timeline_stopped
  File "jellyfin_mpv_shim\rich_presence.py", line 48, in clear_presence
  File "pypresence\client.py", line 143, in clear_activity
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "pypresence\baseclient.py", line 85, in read_output
pypresence.exceptions.InvalidID: Client ID is Invalid
```

**Comment by Banh-Canh** [comment]
i'm having the same issue fyi :/

**Comment by kushvinth** [comment]
```
Traceback (most recent call last):
  File "/Users/MacbookPro/.cache/uv/archive-v0/H9t30dT1e-9uBkZtZvYS1/lib/python3.12/site-packages/jellyfin_mpv_shim/rich_presence.py", line 74, in send_presence
    RPC.set_activity(**payload)
    ^^^
UnboundLocalError: cannot access local variable 'RPC' where it is not associated with a value
2026-05-06 17:33:40,003 [    INFO] update_check: Checking for updates...
2026-05-06 17:33:40,386 [ WARNING] rich_presence: Discord connection lost.
Traceback (most recent call last):
  File "/Users/MacbookPro/.cache/uv/archive-v0/H9t30dT1e-9uBkZtZvYS1/lib/python3.12/site-packages/jellyfin_mpv_shim/rich_presence.py", line 74, in send_presence
    RPC.set_activity(**payload)
    ^^^
UnboundLocalError: cannot access local variable 'RPC' where it is not associated with a value
2026-05-06 17:33:40,592 [ WARNING] rich_presence: Discord connection lost.
Traceback (most recent call last):
  File "/Users/MacbookPro/.cache/uv/archive-v0/H9t30dT1e-9uBkZtZvYS1/lib/python3.12/site-packages/jellyfin_mpv_shim/rich_presence.py", line 74, in send_presence
    RPC.set_activity(**payload)
    ^^^
UnboundLocalError: cannot access local variable 'RPC' where it is not associated with a value
2026-05-06 17:33:46,188 [ WARNING] rich_presence: Discord connection lost.
Traceback (most recent call last):
  File "/Users/MacbookPro/.cache/uv/archive-v0/H9t30dT1e-9uBkZtZvYS1/lib/python3.12/site-packages/jellyfin_mpv_shim/rich_presence.py", line 74, in send_presence
    RPC.set_activity(**payload)
    ^^^
UnboundLocalError: cannot access local variable 'RPC' where it is not associated with a value
2026-05-06 17:33:51,633 [ WARNING] rich_presence: Discord connection lost.
Traceback (most recent call last):
  File "/Users/MacbookPro/.cache/uv/archive-v0/H9t30dT1e-9uBkZtZvYS1/lib/python3.12/site-packages/jellyfin_mpv_shim/rich_presence.py", line 74, in send_presence
    RPC.set_activity(**payload)
    ^^^
UnboundLocalError: cannot access local variable 'RPC' where it is not associated with a value
2026-05-06 17:33:57,905 [ WARNING] rich_presence: Discord connection lost.
Traceback (most recent call last):
  File "/Users/MacbookPro/.cache/uv/archive-v0/H9t30dT1e-9uBkZtZvYS1/lib/python3.12/site-packages/jellyfin_mpv_shim/rich_presence.py", line 74, in send_presence
    RPC.set_activity(**payload)
    ^^^
UnboundLocalError: cannot access local variable 'RPC' where it is not associated with a value
```

i have the same error
