### ISSUE TITLE
MPV shim needs to reconfigured server on every startup

### ISSUE THREAD

**Issue by karserasl** [jellyfin/jellyfin-mpv-shim#344]
**Describe the bug**
The mpv shim on every startup, needs to reconfigure the server to be able to connect.
It does not shown in the cast menu of Jellyfin.
There are sometimes that if i open a second instance of mpv shim on top of the first one, the 2nd one is connected.
**To Reproduce**

1. Jellyfin is running and mpv shim has a working connection
2. Close mpv shim and reopen it 
3. Now it needs to reconfigured the server to get a new connection

**Expected behavior**
It should reconnect on reopen, if the Jellyfin server wasnt restarted before.

**Desktop (please complete the following information):**
 - OS: Windows (mpv-shim), Linux (Jellyfin)
 - Version 2.6.0. latest for Jellyfin

**Error Messages**

> 2023-07-23 16:17:05,784 [ WARNING] clients: Partially connected. Retrying 3/3.
> 2023-07-23 16:17:06,797 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.client: JellyfinClient initializing...
> 2023-07-23 16:17:06,797 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Configuration initializing...
> 2023-07-23 16:17:06,797 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin http constructor.
> 2023-07-23 16:17:06,797 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: WSClient initializing...
> 2023-07-23 16:17:06,797 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: ConnectionManager initializing...
> 2023-07-23 16:17:06,797 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: Credentials initializing...
> 2023-07-23 16:17:06,797 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin app constructor.
> 2023-07-23 16:17:06,797 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin connect
> 2023-07-23 16:17:06,797 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin getAvailableServers
> 2023-07-23 16:17:06,797 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: credentialsupdated
> 2023-07-23 16:17:06,797 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connect has 1 servers
> 2023-07-23 16:17:06,797 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connect_to_server
> 2023-07-23 16:17:06,797 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
> 2023-07-23 16:17:06,797 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
> 2023-07-23 16:17:06,797 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 'X-Application': 'Jellyfin MPV Shim/2.6.0', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/2.6.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=desk, DeviceId=71e96c66-c531-42ff-8393-f1e78331418b, Version=2.6.0'}
> 2023-07-23 16:17:06,798 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 192.168.xxx.xxx:8097
> 2023-07-23 16:17:06,802 [   DEBUG] urllib3.connectionpool: http://192.168.xxx.xxx:8097 "GET /system/info/public HTTP/1.1" 200 None
> 2023-07-23 16:17:06,802 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: calling onSuccessfulConnection with server Tzelly
> 2023-07-23 16:17:06,802 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info
> 2023-07-23 16:17:06,802 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
> 2023-07-23 16:17:06,802 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 'X-Application': 'Jellyfin MPV Shim/2.6.0', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/2.6.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=desk, DeviceId=71e96c66-c531-42ff-8393-f1e78331418b, Version=2.6.0', 'X-MediaBrowser-Token': 'REDACTED'}
> 2023-07-23 16:17:06,803 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 192.168.xxx.xxx:8097
> 2023-07-23 16:17:06,832 [   DEBUG] urllib3.connectionpool: http://192.168.xxx.xxx:8097 "GET /system/info HTTP/1.1" 200 None
> 2023-07-23 16:17:06,833 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: credentialsupdated
> 2023-07-23 16:17:06,833 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: resolving connect with result: {'Servers': "[{'address': 'http://192.168.xxx.xxx:8097', 'Name': 'Tzelly', 'Id': '6f36b8a495fb46ba9b9af34aa7c6dd23', 'DateLastAccessed': '2023-07-23T16:17:06Z', 'UserId': '0e428c4cff3d4adcb1288ec84d4165e1', 'AccessToken': 'REDACTED', 'Users': [{'Id': '0e428c4cff3d4adcb1288ec84d4165e1', 'IsSignedInOffline': True}], 'uuid': '8f1e2218-7505-479b-b780-d8af240602ea', 'username': 'lam', 'connected': True}]", 'State': 3}
> 2023-07-23 16:17:06,833 [    INFO] JELLYFIN.jellyfin_apiclient_python.client: User is authenticated.
> 2023-07-23 16:17:06,833 [   DEBUG] urllib3.util.retry: Converted retries value: 3 -> 'Retry(total=3, connect=None, read=None, redirect=None, status=None)'
> 2023-07-23 16:17:06,833 [   DEBUG] urllib3.util.retry: Converted retries value: 3 -> 'Retry(total=3, connect=None, read=None, redirect=None, status=None)'
> 2023-07-23 16:17:06,833 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: Websocket url: ws://192.168.xxx.xxx:8097/socket?api_key=REDACTEDREDACTED&device_id=71e96c66-c531-42ff-8393-f1e78331418b
> 2023-07-23 16:17:06,834 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 192.168.xxx.xxx:8097
> 2023-07-23 16:17:06,841 [    INFO] websocket: Websocket connected
> 2023-07-23 16:17:06,841 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: --->[ websocket ]
> 2023-07-23 16:17:06,841 [   DEBUG] event_handler: Unhandled Event WebSocketConnect: None
> 2023-07-23 16:17:07,628 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: ForceKeepAlive received from server.
> 2023-07-23 16:17:07,628 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: KeepAlive received from server.
> 2023-07-23 16:17:08,653 [   DEBUG] urllib3.connectionpool: http://192.168.xxx.xxx:8097 "POST /Sessions/Capabilities/Full HTTP/1.1" 204 0
> 2023-07-23 16:17:08,657 [   DEBUG] urllib3.connectionpool: http://192.168.xxx.xxx:8097 "GET /Sessions?ControllableByUserId=0e428c4cff3d4adcb1288ec84d4165e1 HTTP/1.1" 200 None
> 2023-07-23 16:17:08,657 [ WARNING] clients: Client is not actually connected. (It does not show in the client list.)
>

**Comment by vincejv** [comment]
> Desktop (please complete the following information):
OS: Windows (mpv-shim), Linux (Jellyfin)

Same issue on MPV-Shim for Linux, on Ubuntu 22.04.03 LTS, Kernel 6.6.8, MPV Shim 2.6.0, it does not happen consistently though, sometimes it needs to be reconfigured, sometimes it does not

**Comment by G2COMMANDER** [comment]
as mentioned by Izzie in [Issue 331](https://github.com/jellyfin/jellyfin-mpv-shim/issues/331), it appears to have been "enable_osc" being enabled. My fix was to change "enable_osc" to false which solved my "reconnecting" problem.

I'm currently running MPV Shim 2.6.0 on kernel 6.1.0-13-amd64  Debian 6.1.55-1 (2023-09-29) (MX Linux)

**Comment by willforde** [comment]
Unfortunately disabling "enable_osc" did not fix it for me. :disappointed: 
I have tried a few other things but no go.

**Comment by vincejv** [comment]
Does shim need this fix?
https://github.com/jellyfin/jellyfin-web/pull/5566

It fixes itself after a couple of restarts (restart of mpv shim), seems to exhibit the same behavior before that bug was fixed in jellyfin-web

> Having an address that is not always connectable causes our Android users to be unable to reliably connect to the server. It also breaks many reverse-proxy setups, as this address exposed by the server usually bypasses the proxy unless explicitly configured by the user. This has far more negative impact than the benifit it brings.

**Comment by jweymarn** [comment]
I seem to be experiencing the same thing. It was working fine first time. Rebooted and now could not see shim in the cast menu. Shim shows server "ok" in Server Configuration. 
Console shows: 

> [ WARNING] clients: Client is not actually connected. (It does not show in the client list.)

Removing the server and adding it again fixes it. Until next reboot.

Running most recent shim version on Win 11.

**Comment by LiteralGenie** [comment]
In my case the initial connection attempt fails and, under the default config, jellyfin-mpv-shim never tries again.
(The connection fails because I have it start on boot and wifi takes a while to connect.)

When it fails like the this, I get a log like (below)
<blockquote>
<details>
<summary>log</summary>

```
2025-09-30 19:31:38,422 [ WARNING] player: Could not find libmpv.
2025-09-30 19:31:38,422 [    INFO] player: Using external mpv playback backend.
2025-09-30 19:31:38,532 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin connect
2025-09-30 19:31:38,532 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin getAvailableServers
2025-09-30 19:31:38,532 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connect has 1 servers
2025-09-30 19:31:38,532 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connect_to_server
2025-09-30 19:31:38,532 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2025-09-30 19:31:43,543 [   ERROR] JELLYFIN.jellyfin_apiclient_python.connection_manager: Traceback (most recent call last):
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connection.py", line 221, in _new_conn
    sock = self._resolver.create_connection(
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/contrib/resolver/protocols.py", line 296, in create_connection
    raise err
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/contrib/resolver/protocols.py", line 266, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1704, in urlopen
    response = self._make_request(  # type: ignore[call-overload,misc]
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1248, in _make_request
    raise new_e
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1224, in _make_request
    self._validate_conn(conn)
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 779, in _validate_conn
    conn.connect()
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connection.py", line 270, in connect
    self.sock = self._new_conn()
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connection.py", line 236, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x704e70b697e0>, 'Connection to 192.168.2.1 timed out. (connect timeout=5)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/_/.local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1782, in urlopen
    retries = retries.increment(
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 544, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.2.1', port=8096): Max retries exceeded with url: /system/info/public (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x704e70b697e0>, 'Connection to 192.168.2.1 timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/_/.local/lib/python3.10/site-packages/jellyfin_apiclient_python/connection_manager.py", line 190, in connect_to_server
    result = self.API.get_public_info(server.get('address'), self.session)
  File "/home/_/.local/lib/python3.10/site-packages/jellyfin_apiclient_python/api.py", line 827, in get_public_info
    response = self.send_request(server_address, "system/info/public", session=session)
  File "/home/_/.local/lib/python3.10/site-packages/jellyfin_apiclient_python/api.py", line 788, in send_request
    return request_method(url, **request_settings)
  File "/home/_/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/_/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/_/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/_/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/_/.local/lib/python3.10/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.2.1', port=8096): Max retries exceeded with url: /system/info/public (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x704e70b697e0>, 'Connection to 192.168.2.1 timed out. (connect timeout=5)'))

2025-09-30 19:31:43,543 [   ERROR] JELLYFIN.jellyfin_apiclient_python.connection_manager: Failing server connection. ERROR msg: HTTPConnectionPool(host='192.168.2.1', port=8096): Max retries exceeded with url: /system/info/public (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x704e70b697e0>, 'Connection to 192.168.2.1 timed out. (connect timeout=5)'))
2025-09-30 19:31:43,543 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin connect
2025-09-30 19:31:43,543 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin getAvailableServers
2025-09-30 19:31:43,543 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connect has 1 servers
2025-09-30 19:31:43,544 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connect_to_server
2025-09-30 19:31:43,544 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2025-09-30 19:31:48,552 [   ERROR] JELLYFIN.jellyfin_apiclient_python.connection_manager: Traceback (most recent call last):
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connection.py", line 221, in _new_conn
    sock = self._resolver.create_connection(
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/contrib/resolver/protocols.py", line 296, in create_connection
    raise err
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/contrib/resolver/protocols.py", line 266, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1704, in urlopen
    response = self._make_request(  # type: ignore[call-overload,misc]
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1248, in _make_request
    raise new_e
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1224, in _make_request
    self._validate_conn(conn)
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 779, in _validate_conn
    conn.connect()
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connection.py", line 270, in connect
    self.sock = self._new_conn()
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connection.py", line 236, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x704e70b68430>, 'Connection to 192.168.2.1 timed out. (connect timeout=5)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/_/.local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1782, in urlopen
    retries = retries.increment(
  File "/home/_/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 544, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.2.1', port=8097): Max retries exceeded with url: /system/info/public (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x704e70b68430>, 'Connection to 192.168.2.1 timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/_/.local/lib/python3.10/site-packages/jellyfin_apiclient_python/connection_manager.py", line 190, in connect_to_server
    result = self.API.get_public_info(server.get('address'), self.session)
  File "/home/_/.local/lib/python3.10/site-packages/jellyfin_apiclient_python/api.py", line 827, in get_public_info
    response = self.send_request(server_address, "system/info/public", session=session)
  File "/home/_/.local/lib/python3.10/site-packages/jellyfin_apiclient_python/api.py", line 788, in send_request
    return request_method(url, **request_settings)
  File "/home/_/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/_/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/_/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/_/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/_/.local/lib/python3.10/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.2.1', port=8097): Max retries exceeded with url: /system/info/public (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x704e70b68430>, 'Connection to 192.168.2.1 timed out. (connect timeout=5)'))

2025-09-30 19:31:48,552 [   ERROR] JELLYFIN.jellyfin_apiclient_python.connection_manager: Failing server connection. ERROR msg: HTTPConnectionPool(host='192.168.2.1', port=8097): Max retries exceeded with url: /system/info/public (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x704e70b68430>, 'Connection to 192.168.2.1 timed out. (connect timeout=5)'))
```

</details>
</blockquote>


To fix this, I changed `connect_retry_mins` in `conf.json` from 0 to 999. This tells jellyfin-mpv-shim to [attempt a reconnect](https://github.com/jellyfin/jellyfin-mpv-shim/blob/e1fd6dcd62a531aa63da6df1ddad59f162a48530/jellyfin_mpv_shim/clients.py#L134)every 30s for 999 minutes.
