### ISSUE TITLE
[macOS] Unable to set video playback filters

### ISSUE THREAD

**Issue by glottisfaun0000** [jellyfin/jellyfin-mpv-shim#356]
After installing on macOS using the installation steps with brew and pip3, the one feature I can't get working is the filters like Anime4k. Here's what the output says when I try to select a filter in the `c` menu:
```
2023-12-19 18:00:55,903 [ WARNING] player: Error when processing client-message.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/jellyfin_mpv_shim/player.py", line 445, in handle_client_message
    self.menu.menu_action("ok")
  File "/opt/homebrew/lib/python3.11/site-packages/jellyfin_mpv_shim/menu.py", line 247, in menu_action
    self.menu_list[self.menu_selection][1]()
  File "/opt/homebrew/lib/python3.11/site-packages/jellyfin_mpv_shim/video_profile.py", line 179, in menu_handle
    settings_were_successful = self.load_profile(profile_name)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jellyfin_mpv_shim/video_profile.py", line 148, in load_profile
    setattr(self.player, key, value)
  File "/opt/homebrew/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 648, in __setattr__
    return self.command("set_property", name.replace("_", "-"), value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 639, in command
    return self.mpv_inter.command(command, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 347, in command
    raise MPVError(data["error"])
python_mpv_jsonipc.MPVError: unsupported format for accessing property
```

Tried in and out of a venv, same result. Any ideas?

**Comment by L3tum** [comment]
Interestingly I have the same issue on Windows, just with a different error of "Could not open file ''".

**Comment by Ryptahi** [comment]
> After installing on macOS using the installation steps with brew and pip3, the one feature I can't get working is the filters like Anime4k. Here's what the output says when I try to select a filter in the `c` menu:
> 
> ```
> 2023-12-19 18:00:55,903 [ WARNING] player: Error when processing client-message.
> Traceback (most recent call last):
>   File "/opt/homebrew/lib/python3.11/site-packages/jellyfin_mpv_shim/player.py", line 445, in handle_client_message
>     self.menu.menu_action("ok")
>   File "/opt/homebrew/lib/python3.11/site-packages/jellyfin_mpv_shim/menu.py", line 247, in menu_action
>     self.menu_list[self.menu_selection][1]()
>   File "/opt/homebrew/lib/python3.11/site-packages/jellyfin_mpv_shim/video_profile.py", line 179, in menu_handle
>     settings_were_successful = self.load_profile(profile_name)
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/jellyfin_mpv_shim/video_profile.py", line 148, in load_profile
>     setattr(self.player, key, value)
>   File "/opt/homebrew/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 648, in __setattr__
>     return self.command("set_property", name.replace("_", "-"), value)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 639, in command
>     return self.mpv_inter.command(command, *args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 347, in command
>     raise MPVError(data["error"])
> python_mpv_jsonipc.MPVError: unsupported format for accessing property
> ```
> 
> Tried in and out of a venv, same result. Any ideas?

Had same issue. I was able to get the shaders like anime4k working by going to jellyfin-mpv-shim folder and using the anime4k input as normal to change to correct shader. Seems like it will remember the one you changed to previously. Not ideal solution, but good enough at least for me.

**Comment by NanoCode012** [comment]
Ok, I did a bit of debugging. There's two problems to this:
- Mac uses `vulcan`, not `opengl` (fixes original problem) https://github.com/iwalton3/default-shader-pack/blob/ca506a6bf3937881ebd1ab35bfbaf3d9b0221e0d/pack-next.json#L15
- `dither=fruit` causes it to crash https://github.com/iwalton3/default-shader-pack/blob/ca506a6bf3937881ebd1ab35bfbaf3d9b0221e0d/pack-next.json#L67

**Solution**: go update the `default-shader-pack`'s `pack-next.json` to swap to `vulkan` and remove `dither=fruit`.

The path for me (with miniconda base) was : `~/miniconda3/lib/python3.10/site-packages/jellyfin_mpv_shim/default_shader_pack/pack-next.json`.

A cleaner method may be to duplicate the shader folder and use `shader_pack_custom`, but there was some other issue and I didn't want to debug further.

**Comment by codeswhite** [comment]
@iwalton3 
MacOS has dropped support for OpenGL 7 years ago, and now uses Vulkan primarily.

Can we think of a clean solution on the code level?
Maybe:
- try-catch load opengl and fallback to vulkan if opengl fails
- automatically use vulkan if running on macos platform

What do you think?

**Comment by iwalton3** [comment]
I'd just do an if/else check and if it is MacOS apply the correct parameters to mpv.

**Comment by codeswhite** [comment]
I just tried to reproduce and wasnt able to make the shaders work even after @NanoCode012 's tweaks...

Log says:
```
2025-04-05 19:25:44,553 [    INFO] video_profile: Unloading shader profile.
2025-04-05 19:25:44,554 [    INFO] video_profile: Loading shader profile generic.
2025-04-05 19:25:44,554 [    INFO] video_profile: Set MPV setting deband to True
2025-04-05 19:25:44,558 [    INFO] video_profile: Set MPV setting deband_grain to 0
2025-04-05 19:25:44,588 [    INFO] video_profile: Set MPV setting deband_range to 12
2025-04-05 19:25:44,607 [    INFO] video_profile: Set MPV setting deband_threshold to 32
2025-04-05 19:25:44,624 [    INFO] video_profile: Set MPV setting hwdec to auto-copy
2025-04-05 19:25:44,625 [    INFO] video_profile: Set MPV setting profile to gpu-hq
2025-04-05 19:25:44,626 [    INFO] video_profile: Set MPV setting gpu_api to **vulkan**
2025-04-05 19:25:44,798 [    INFO] video_profile: Set MPV setting fbo_format to rgba16f
2025-04-05 19:25:44,893 [    INFO] video_profile: Set MPV setting dither_depth to auto
2025-04-05 19:25:44,901 [    INFO] video_profile: Set MPV setting scale to ewa_lanczos
2025-04-05 19:25:44,902 [    INFO] video_profile: Set MPV setting dscale to mitchell
2025-04-05 19:25:44,903 [    INFO] video_profile: Set MPV setting linear_downscaling to no
2025-04-05 19:25:44,903 [    INFO] video_profile: Set MPV setting cscale to mitchell
2025-04-05 19:25:44,904 [    INFO] video_profile: Set shaders: ['/Users/x/.local/pipx/venvs/jellyfin-mpv-shim/lib/python3.13/site-packages/jellyfin_mpv_shim/default_shader_pack/shaders/noise_static_luma.hook', '/Users/x/.local/pipx/venvs/jellyfin-mpv-shim/lib/python3.13/site-packages/jellyfin_mpv_shim/default_shader_pack/shaders/noise_static_chroma.hook', '/Users/x/.local/pipx/venvs/jellyfin-mpv-shim/lib/python3.13/site-packages/jellyfin_mpv_shim/default_shader_pack/shaders/FSRCNNX_x2_8-0-4-1.glsl', '/Users/x/.local/pipx/venvs/jellyfin-mpv-shim/lib/python3.13/site-packages/jellyfin_mpv_shim/default_shader_pack/shaders/SSimDownscaler.glsl', '/Users/x/.local/pipx/venvs/jellyfin-mpv-shim/lib/python3.13/site-packages/jellyfin_mpv_shim/default_shader_pack/shaders/KrigBilateral.glsl']
2025-04-05 19:25:44,908 [    INFO] mpv: vd: Using hardware decoding (videotoolbox-copy).
2025-04-05 19:25:44,908 [   ERROR] mpv: ffmpeg/video: h264: co located POCs unavailable
2025-04-05 19:25:44,908 [ WARNING] mpv: ffmpeg/video: h264: vt decoder cb: output image buffer is null: -12909
2025-04-05 19:25:44,908 [   ERROR] mpv: ffmpeg/video: h264: hardware accelerator failed to decode picture
2025-04-05 19:25:44,908 [ WARNING] mpv: vd: Error while decoding frame (hardware decoding)!
2025-04-05 19:25:44,909 [ WARNING] mpv: ffmpeg/video: h264: vt decoder cb: output image buffer is null: -12909
2025-04-05 19:25:44,909 [   ERROR] mpv: ffmpeg/video: h264: hardware accelerator failed to decode picture
2025-04-05 19:25:44,909 [ WARNING] mpv: vd: Error while decoding frame (hardware decoding)!
2025-04-05 19:25:44,909 [   ERROR] mpv: ffmpeg/video: h264: mmco: unref short failure
2025-04-05 19:25:44,909 [ WARNING] mpv: ffmpeg/video: h264: vt decoder cb: output image buffer is null: -12909
2025-04-05 19:25:44,909 [   ERROR] mpv: ffmpeg/video: h264: hardware accelerator failed to decode picture
2025-04-05 19:25:44,909 [ WARNING] mpv: vd: Error while decoding frame (hardware decoding)!
2025-04-05 19:25:44,909 [   ERROR] mpv: ffmpeg/video: h264: co located POCs unavailable
2025-04-05 19:25:44,909 [   ERROR] mpv: ffmpeg/video: h264: mmco: unref short failure
2025-04-05 19:25:44,942 [    INFO] mpv: cplayer: VO: [gpu] 1920x1080 yuv420p
```
