### ISSUE TITLE
Flatpak Version not running

### ISSUE THREAD

**Issue by Simon1511** [jellyfin/jellyfin-mpv-shim#359]
**Describe the bug**
When running `flatpak run com.github.iwalton3.jellyfin-mpv-shim` or clicking the Desktop icon Jellyfin should open, but it doesn't.

**To Reproduce**
1. Install the Flatpak Version (flatpak install flathub com.github.iwalton3.jellyfin-mpv-shim)
2. Click the Desktop icon or run `flatpak run com.github.iwalton3.jellyfin-mpv-shim`
3. Observe nothing opening, despite the command not exiting after running it.
4. See error message

**Expected behavior**
Jellyfin should open normally.

**Screenshots**
None.

**Desktop:**
 - OS: Fedora
 - Version 39

**Error Messages**
```
~$ flatpak run com.github.iwalton3.jellyfin-mpv-shim
2024-01-03 13:13:34,231 [    INFO] conf: Loaded settings from json: /home/simon/.var/app/com.github.iwalton3.jellyfin-mpv-shim/config/jellyfin-mpv-shim/conf.json
2024-01-03 13:13:34,272 [    INFO] player: Using libmpv1 playback backend.
Tk_Init error: no display name and no $DISPLAY environment variable
Process PreferencesWindowProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/app/lib/python3.10/site-packages/jellyfin_mpv_shim/gui_mgr.py", line 281, in run
    root = tk.Tk()
  File "/app/lib/python3.10/site-packages/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

(jellyfin-mpv-shim:19): Gdk-WARNING **: 13:13:34.363: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop

(jellyfin-mpv-shim:19): Gtk-WARNING **: 13:13:34.410: Locale not supported by C library.
	Using the fallback 'C' locale.
2024-01-03 13:13:34,421 [   DEBUG] PIL.PngImagePlugin: STREAM "b'IHDR'" 16 13
2024-01-03 13:13:34,421 [   DEBUG] PIL.PngImagePlugin: STREAM "b'pHYs'" 41 9
2024-01-03 13:13:34,421 [   DEBUG] PIL.PngImagePlugin: STREAM "b'IDAT'" 62 709

(jellyfin-mpv-shim:19): Gtk-CRITICAL **: 13:13:34.546: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

** (jellyfin-mpv-shim:19): WARNING **: 13:13:59.448: atk-bridge: get_device_events_reply: unknown signature
^C
Traceback (most recent call last):
  File "/app/bin/jellyfin-mpv-shim", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.10/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 79, in main
    user_interface.login_servers()
  File "/app/lib/python3.10/site-packages/jellyfin_mpv_shim/gui_mgr.py", line 408, in login_servers
    self.preferences_window.block_until_close()
  File "/app/lib/python3.10/site-packages/jellyfin_mpv_shim/gui_mgr.py", line 210, in block_until_close
    self.dead_trigger.wait()
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
```

The actual error seems to be: `Tk_Init error: no display name and no $DISPLAY environment variable`

**Comment by cameronj86** [comment]
https://github.com/jellyfin/jellyfin-mpv-shim/issues/219#issuecomment-1263928032

**Comment by Simon1511** [comment]
Thanks, didn't know that. Closing this then.
