### ISSUE TITLE
Getting started: so HOW do you WATCH something?

### ISSUE THREAD

**Issue by tdbe** [jellyfin/jellyfin-mpv-shim#369]
Hey, terribly sorry but just was checking this out and I feel stupid. I installed it, configured it to a server, I have a tray icon, now um.... HOW do you browse and WATCH something? 🙃

**Comment by ahmed2m** [comment]
That's correct -I think- _the client_ for it would be [jellyfin-media-player](https://github.com/jellyfin/jellyfin-media-player) which afaik use mpv as a backend but I have no idea if it plays HDR content or not.

**Comment by dominoto** [comment]
@tdbe You can use the Jellyfin Media Player like @ahmed2m said, or you can use your Jellyfin's server web UI that you can find on `your.server.IP:8096`. In both cases, don't forget to find **Cast to Device** button in top right corner and choose the Shim. You'll maybe need to refresh the page or restart the Shim if it doesn't pick it up on first try.

**Comment by Cappellohack** [comment]
I'm in the same boat, kinda. I know, that you have to "cast to jellyfin-mpv-shim", but the option isn't there.
I'm on Fedora 40 and installed jellyfin-mpv-shim as flatpak. 

When starting it through the terminal, I get this:
`2024-05-28 19:43:20,639 [    INFO] player: Using libmpv1 playback backend.
Tk_Init error: no display name and no $DISPLAY environment variable
Process PreferencesWindowProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/app/lib/python3.11/site-packages/jellyfin_mpv_shim/gui_mgr.py", line 279, in run
    root = tk.Tk()
           ^^^^^^^
  File "/app/lib/python3.11/site-packages/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: no display name and no $DISPLAY environment variable

(jellyfin-mpv-shim:21): Gtk-CRITICAL **: 19:43:21.145: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
2024-05-28 19:48:20,387 [    INFO] clients: Performing client health check...
`

I can see, that the program is running in the background, but it seems to do nothing.
