### ISSUE TITLE
mpv-shim doesn't work with external player memento

### ISSUE THREAD

**Issue by eyalmazuz** [jellyfin/jellyfin-mpv-shim#406]
**Describe the bug**
when setting mpv_ext to use an external player, mpv-shim fails to load when setting the external player to [memento](https://github.com/ripose-jp/Memento) 

**To Reproduce**
1. Install memento on linux
2. Set the config on mpv-shim to the following values
```
"mpv_ext": true, 
"mpv_ext_ipc": null,
"mpv_ext_no_ovr": false,
"mpv_ext_path": "/usr/bin/memento",
"mpv_ext_start": true,
```
3. Open terminal and run ``jellyfin-mpv-shim``
4. memento player opens
5. nothing happens, no system tray, no control keys then after couple of seconds memnto closes and re-opens
6. See error in the terminal

**Expected behavior**
mpv-shim should be able to open and connect with the server like the default mpv player

**Screenshots**
![image](https://github.com/user-attachments/assets/63d1fd78-6322-445f-9bcc-ecc80d9920c5)

P.S. I did keyboard interrupt since it just enters a loop when it opens memento, doesn't comment to anything then throw the MPV start timeout error so it just repeats itself

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Kernel version: 6.6.40-1
 - mpv-shim version: 2.8.0-1
 - memento version: 1.4.0

**Error Messages**
output of logs.txt file:
```
2024-07-26 12:15:03,665 [    INFO] player: Using external mpv playback backend.
2024-07-26 12:15:13,695 [ WARNING] mpv-jsonipc: MPV start failed.
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/python_mpv_jsonipc.py", line 430, in __init__
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/python_mpv_jsonipc.py", line 250, in __init__
    raise MPVError("MPV start timed out.")
python_mpv_jsonipc.MPVError: MPV start timed out.
```

**Comment by eyalmazuz** [comment]
closing as it seems like an issue with memento that was fixed already
https://github.com/ripose-jp/Memento/issues/217
