### ISSUE TITLE
mpv ignores script-opts on mac

### ISSUE THREAD

**Issue by starptr** [jellyfin/jellyfin-mpv-shim#416]
**Describe the bug**
When running `mpv` independently, it correctly reads configurations keys I set in `~/.config/mpv/script-opts/`, but the mpv instance that jellyfin-mpv-shim starts up does not seem to read them.

**To Reproduce**
1. Use a script which reads `~/.config/mpv/script-opts/foo.conf`, such as `webm.conf`.
2. Run `mpv "https://www.youtube.com/watch?v=BQvGUyxbxWc"`
3. Use the script such that it uses a custom conf value that is different from the default.
4. Run `jellyfin-mpv-shim`.
5. Play a video, and use the script similarly such that it is supposed to use a custom conf value that is different from the default.

**Expected behavior**
The custom conf value should be read.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 14.2.1

**Error Messages**
Please provide logs, as they are often needed for me to understand and quickly troubleshoot the issue. You can read instructions for how to do so here:
https://github.com/iwalton3/jellyfin-mpv-shim/wiki/Sending-Logs
```
2024-09-27 00:36:53,098 [ WARNING] root: Cannot load GUI. Falling back to command line interface.
Traceback (most recent call last):
  File "/Users/yuto/src/jellyfin-mpv-shim-bin/.venv/lib/python3.12/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 48, in main
    from .gui_mgr import user_interface
  File "/Users/yuto/src/jellyfin-mpv-shim-bin/.venv/lib/python3.12/site-packages/jellyfin_mpv_shim/gui_mgr.py", line 1, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
2024-09-27 00:36:53,108 [    INFO] player: Using external mpv playback backend.
2024-09-27 00:36:53,109 [   ERROR] player: Could not enable trickplay.
Traceback (most recent call last):
  File "/Users/yuto/src/jellyfin-mpv-shim-bin/.venv/lib/python3.12/site-packages/jellyfin_mpv_shim/player.py", line 173, in __init__
    from .trickplay import TrickPlay
  File "/Users/yuto/src/jellyfin-mpv-shim-bin/.venv/lib/python3.12/site-packages/jellyfin_mpv_shim/trickplay.py", line 7, in <module>
    from . import bifdecode
  File "/Users/yuto/src/jellyfin-mpv-shim-bin/.venv/lib/python3.12/site-packages/jellyfin_mpv_shim/bifdecode.py", line 3, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
2024-09-27 00:36:53,339 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin connect
2024-09-27 00:36:53,339 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin getAvailableServers
2024-09-27 00:36:53,339 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connect has 1 servers
2024-09-27 00:36:53,339 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connect_to_server
2024-09-27 00:36:53,339 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2024-09-27 00:36:54,075 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: calling onSuccessfulConnection with server REDACTED_FOR_GH
2024-09-27 00:36:54,076 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info
2024-09-27 00:36:54,379 [    INFO] JELLYFIN.jellyfin_apiclient_python.client: User is authenticated.
2024-09-27 00:36:54,380 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: Websocket url: wss://REDACTED_FOR_GH
2024-09-27 00:36:54,687 [    INFO] websocket: Websocket connected
2024-09-27 00:36:54,688 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: --->[ websocket ]

~Redacted cplayer logs about the media~

2024-09-27 00:37:04,339 [    INFO] update_check: Checking for updates...
2024-09-27 00:37:17,726 [ WARNING] mpv: cplayer: Warning: property 'sub-ass-force-style' was replaced with 'sub-ass-style-overrides' and might be removed in the future.
2024-09-27 00:37:17,726 [    INFO] mpv: webm: Encoding to /Users/yuto/streamstatic=true&MediaSourceId=5727d5e8da7967e60b70e7f30884ee3e&api_key=REDACTED-[00.09.466-00.12.679]-audio.webm
```

**Comment by starptr** [comment]
Looks like jellyfin-mpv-shim treats `Library/Application Support/jellyfin-mpv-shim` as how vanilla mpv treats `.config/mpv`. I got confused because I thought jellyfin-mpv-shim also used `.config/mpv`, because the external mpv instance it started was running a script that I installed in the vanilla mpv config. However, it turns out that if you use nixpkgs's `pkgs.mpv-unwrapped.wrapper { scripts }` function and pass in `pkgs.mpvScripts.mpv-webm`, it actually builds a version of `mpv` with the script "hardcoded" in (obvious in hindsight; packages built with wrappers from nixpkgs doesn't use `~/.config/mpv/scripts` because they are pure!), so it looks like the script was also being read-in from jellyfin-mpv-shim, when in reality, the script was already in the external mpv distribution.
