### ISSUE TITLE
Cannot add server when the supplied user is not server manager.

### ISSUE THREAD

**Issue by opapanik** [jellyfin/jellyfin-mpv-shim#422]
You cannot add your server if the user has unticked the option "Allow this user to manage the server" on the server.
Is this by design? In order for someone to be able to just use MPV shim to view movies, must I make him a jellyfin server manager???

**To Reproduce**
Just try to add a server with a user that is not a jellyfin server manager.

**Expected behavior**
Non managers should be able to view movies.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10
 - MPV Shim Version 2.8.0
 - Jellyfin server 10.10.0 on Debian
 
**Error Messages**
The following is the full log of the following actions (no servers configured):
1. try to add the server with user "TV17" (fails)
2. changing the user to "user" and adding the server succeeds
3. deleting the succeeded server
4. changing the user to ""TV17" once more and adding the server (fails)

The only differece between "user" and "TV17" is that the former has the box "Allow this user to manage the server" on jellyfin user settings ticked.

Log:

2024-11-03 15:47:30,487 [    INFO] player: Using libmpv1 playback backend.
2024-11-03 15:47:30,500 [    INFO] video_profile: Loading shader profile nnedi-high.
2024-11-03 15:48:01,947 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2024-11-03 15:48:01,971 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connect_to_address http://delltop:8096 succeeded
2024-11-03 15:48:01,971 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connect_to_server
2024-11-03 15:48:01,971 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2024-11-03 15:48:02,000 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: calling onSuccessfulConnection with server None
2024-11-03 15:48:02,000 [    INFO] JELLYFIN.jellyfin_apiclient_python.credentials: {}
2024-11-03 15:48:02,000 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Trying to login to http://delltop:8096/Users/AuthenticateByName as user
2024-11-03 15:48:02,000 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending post request to Users/AuthenticateByName
2024-11-03 15:48:02,346 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Succesfully logged in as user
2024-11-03 15:48:02,348 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin connect
2024-11-03 15:48:02,348 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin getAvailableServers
2024-11-03 15:48:02,348 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connect has 1 servers
2024-11-03 15:48:02,348 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connect_to_server
2024-11-03 15:48:02,348 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2024-11-03 15:48:02,378 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: calling onSuccessfulConnection with server EPafin
2024-11-03 15:48:02,378 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info
2024-11-03 15:48:02,416 [    INFO] JELLYFIN.jellyfin_apiclient_python.client: User is authenticated.
2024-11-03 15:48:02,416 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: Websocket url: ws://delltop:8096/socket?api_key=REDACTEDREDACTED&device_id=61d25003-00a0-46ba-a109-e9b42f1cac7b
2024-11-03 15:48:02,434 [    INFO] websocket: Websocket connected
2024-11-03 15:48:02,434 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: --->[ websocket ]
2024-11-03 15:48:34,577 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: ---<[ websocket ]
2024-11-03 15:48:34,577 [    INFO] Jellyfin.jellyfin_apiclient_python.http: --<[ session/1875024977824 ]
2024-11-03 15:48:43,226 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2024-11-03 15:48:43,257 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connect_to_address http://delltop:8096 succeeded
2024-11-03 15:48:43,257 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connect_to_server
2024-11-03 15:48:43,257 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2024-11-03 15:48:43,272 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: calling onSuccessfulConnection with server None
2024-11-03 15:48:43,272 [    INFO] JELLYFIN.jellyfin_apiclient_python.credentials: {}
2024-11-03 15:48:43,273 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Trying to login to http://delltop:8096/Users/AuthenticateByName as TV17
2024-11-03 15:48:43,273 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending post request to Users/AuthenticateByName
2024-11-03 15:48:43,622 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Succesfully logged in as TV17
2024-11-03 15:48:43,622 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin connect
2024-11-03 15:48:43,622 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin getAvailableServers
2024-11-03 15:48:43,622 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connect has 1 servers
2024-11-03 15:48:43,623 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connect_to_server
2024-11-03 15:48:43,623 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2024-11-03 15:48:43,648 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: calling onSuccessfulConnection with server EPafin
2024-11-03 15:48:43,648 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info
2024-11-03 15:48:43,681 [    INFO] JELLYFIN.jellyfin_apiclient_python.client: User is authenticated.
2024-11-03 15:48:43,681 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: Websocket url: ws://delltop:8096/socket?api_key=REDACTEDREDACTED&device_id=61d25003-00a0-46ba-a109-e9b42f1cac7b
2024-11-03 15:48:43,687 [    INFO] websocket: Websocket connected
2024-11-03 15:48:43,687 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: --->[ websocket ]
2024-11-03 15:48:43,693 [   ERROR] Jellyfin.jellyfin_apiclient_python.http: 500 Server Error: Internal Server Error for url: http://delltop:8096/Sessions?ControllableByUserId=2252db7c09b34e24b80ae4de05e75359
2024-11-03 15:48:43,693 [   ERROR] Jellyfin.jellyfin_apiclient_python.http: --[ 500 response ] 500 Server Error: Internal Server Error for url: http://delltop:8096/Sessions?ControllableByUserId=2252db7c09b34e24b80ae4de05e75359
2024-11-03 15:48:43,694 [   ERROR] gui_mgr: Error while adding server.
Traceback (most recent call last):
  File "jellyfin_mpv_shim\gui_mgr.py", line 189, in run
  File "jellyfin_mpv_shim\clients.py", line 174, in login
  File "jellyfin_mpv_shim\clients.py", line 254, in connect_client
  File "jellyfin_mpv_shim\clients.py", line 226, in setup_client
  File "jellyfin_mpv_shim\clients.py", line 181, in validate_client
TypeError: 'NoneType' object is not iterable

**Comment by hemicyon** [comment]
I've been getting this same error recently on a server I'm not a manager of, though it had been working fine for the month or so since I first installed it.
